# Generated by Django 2.2.10 on 2021-10-14 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Вопрос к опросу',
                'verbose_name_plural': 'Вопросы к опросам',
            },
        ),
        migrations.AlterField(
            model_name='poll',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='end_date',
            field=models.DateTimeField(verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='start_date',
            field=models.DateTimeField(verbose_name='Дата старта'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=200, verbose_name='Текст вопроса'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('text', 'Ответ текстом'), ('one', 'Выбор одного варианта'), ('several', 'Выбор нескольких вариантов')], default='text', max_length=20, verbose_name='Тип вопроса'),
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=200, verbose_name='Ответ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.PollQuestion', verbose_name='Вопрос')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Ответ на вопрос',
                'verbose_name_plural': 'Ответы на вопросы',
            },
        ),
        migrations.AddField(
            model_name='pollquestion',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_in', to='api.Poll', verbose_name='Опрос'),
        ),
        migrations.AddField(
            model_name='pollquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_in', to='api.Question', verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='poll',
            name='questions',
            field=models.ManyToManyField(through='api.PollQuestion', to='api.Question'),
        ),
        migrations.AddConstraint(
            model_name='useranswer',
            constraint=models.UniqueConstraint(fields=('question', 'answer'), name='unique_question_answer'),
        ),
        migrations.AddConstraint(
            model_name='pollquestion',
            constraint=models.UniqueConstraint(fields=('poll', 'question'), name='unique_poll_question'),
        ),
    ]
