# Generated by Django 2.2.10 on 2021-10-14 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211014_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='user',
            field=models.PositiveIntegerField(verbose_name='Id анонимного пользователя'),
        ),
    ]
